### ISSUE TITLE
Workbox compilation on master throws warnings

### ISSUE THREAD

**Issue by prateekbh** [preactjs/preact-cli#1174]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**
Service worker compilation throws
```
        Duplicate declaration '_iterator2 = _isArray2 ? _iterator2 : _iterator2[Symbol.iterator]()'
        Duplicate declaration '_iterator3 = _isArray3 ? _iterator3 : _iterator3[Symbol.iterator]()'
        Duplicate declaration '_iterator4 = _isArray4 ? _iterator4 : _iterator4[Symbol.iterator]()'
        Duplicate declaration '_iterator = _isArray ? _iterator : _iterator[Symbol.iterator]()'
        Duplicate declaration '_iterator2 = _isArray2 ? _iterator2 : _iterator2[Symbol.iterator]()'
        Duplicate declaration '_iterator3 = _isArray3 ? _iterator3 : _iterator3[Symbol.iterator]()'
        Duplicate declaration '_iterator4 = _isArray4 ? _iterator4 : _iterator4[Symbol.iterator]()'
        Duplicate declaration '_iterator = _isArray ? _iterator : _iterator[Symbol.iterator]()'
        Duplicate declaration '_iterator2 = _isArray2 ? _iterator2 : _iterator2[Symbol.iterator]()'
        Duplicate declaration '_iterator3 = _isArray3 ? _iterator3 : _iterator3[Symbol.iterator]()'
        Duplicate declaration '_iterator = _isArray ? _iterator : _iterator[Symbol.iterator]()'
        Duplicate declaration '_iterator2 = _isArray2 ? _iterator2 : _iterator2[Symbol.iterator]()'
        Duplicate declaration '_iterator3 = _isArray3 ? _iterator3 : _iterator3[Symbol.iterator]()'
```

**If the current behaviour is a bug, please provide the steps to reproduce.**
run preact build with master branch

**What is the expected behaviour?**
Service worker should compile without warnings

**Comment by prateekbh** [comment]
this is coming from including `workbox-precaching` package. still investigating why

**Comment by prateekbh** [comment]
this might be due to version mismatch.

After updating to latest removing old `workbox` node_modules should do the trick

**Comment by reznord** [comment]
Fixed in the latest rc - [3.0.0-rc.16](https://github.com/preactjs/preact-cli/tree/3.0.0-rc.16)

**Comment by psabharwal123** [comment]
still seeing this in "preact-cli": "^3.0.1", when will this be released?
