### ISSUE TITLE
--no-prerenderer does not seems to be recognized in 3.0.3

### ISSUE THREAD

**Issue by evaisse** [preactjs/preact-cli#1511]
**Do you want to request a _feature_ or report a _bug_?**

I report for I believe a bug, or at least a very misconducting error message...

**What is the current behaviour?**

by just doing 

`./node_modules/.bin/preact build --no-prerenderer` in my project (preact-cli at 3.0.3)

I get the following error :

```
ReferenceError: window is not defined
method: QfWi
at: /Users/evaisse/Sites/projects/comulist/comulist-preact-pwa/src/store.js:16:0

Source code:

    firebase.app();
}
window.firebase = firebase;
export {
    firebase,

This is most likely caused by using DOM or Web APIs.
Pre-render runs in node and has no access to globals available in browsers.

Consider wrapping code producing error in: 'if (typeof window !== "undefined") { ... }'

Alternatively use 'preact build --no-prerender' to disable prerendering.

See https://github.com/developit/preact-cli#pre-rendering for further information.
```

**If the current behaviour is a bug, please provide the steps to reproduce.**

I suppose you could easily reproduce by pasting this code into index.js

```
import firebase from "firebase/app";
import firebaseConfig from './firebase.config';

window.firebase = firebase;

export {
    firebase,
};
```

**What is the expected behaviour?**

So I think the problem is mainly with the `--no-prerenderer` argument which is also not in the man page for the preact-cli command : 

```
evaisse@macbookpro16 comulist-preact-pwa % ./node_modules/.bin/preact build -h              

  Description
    Create a production build.
    You can disable "default: true" flags by prefixing them with --no-<option>

  Usage
    $ preact build [src] [options]

  Options
    --src              Specify source directory  (default src)
    --dest             Specify output directory  (default build)
    --cwd              A directory to use instead of $PWD  (default .)
    --esm              Builds ES-2015 bundles for your code  (default true)
    --sw               Generate and attach a Service Worker  (default true)
    --babelConfig      Path to custom Babel config  (default .babelrc)
    --json             Generate build stats for bundle analysis
    --template         Path to custom HTML template
    --preload          Adds preload tags to the document its assets  (default false)
    --analyze          Launch interactive Analyzer to inspect production bundle(s)
    --prerenderUrls    Path to pre-rendered routes config  (default prerender-urls.json)
    --brotli           Builds brotli compressed bundles of javascript  (default false)
    --inline-css       Adds critical css to the prerendered markup  (default true)
    -c, --config       Path to custom CLI config  (default preact.config.js)
    -v, --verbose      Verbose output
    -h, --help         Displays this message
```

**Comment by rschristian** [comment]
This was fixed in #1490

Please update to v3.0.4.

Also, the flag is `--no-prerender`. You have an extra "er" there.

**Comment by evaisse** [comment]
indeed, I did mistype  the name, but it is still not working there is no trace of this option in the man page of build command in 3.0.4

```
% ./node_modules/.bin/preact -v          
preact, 3.0.4

 % ./node_modules/.bin/preact build --no-prerender 
✖ ERROR Invalid argument prerender passed to build. Please refer to 'preact build --help' for full list of options.


% ./node_modules/.bin/preact build --help

  Description
    Create a production build.
    You can disable "default: true" flags by prefixing them with --no-<option>

  Usage
    $ preact build [src] [options]

  Options
    --src              Specify source directory  (default src)
    --dest             Specify output directory  (default build)
    --cwd              A directory to use instead of $PWD  (default .)
    --esm              Builds ES-2015 bundles for your code  (default true)
    --sw               Generate and attach a Service Worker  (default true)
    --babelConfig      Path to custom Babel config  (default .babelrc)
    --json             Generate build stats for bundle analysis
    --template         Path to custom HTML template
    --preload          Adds preload tags to the document its assets  (default false)
    --analyze          Launch interactive Analyzer to inspect production bundle(s)
    --prerenderUrls    Path to pre-rendered routes config  (default prerender-urls.json)
    --brotli           Builds brotli compressed bundles of javascript  (default false)
    --inline-css       Adds critical css to the prerendered markup  (default true)
    -c, --config       Path to custom CLI config  (default preact.config.js)
    -v, --verbose      Verbose output
    -h, --help         Displays this message

```

**Comment by rschristian** [comment]
@evaisse You said you were on v3.0.3. This is why that bottom chunk (`preact info`) is important.

This was a bug resolved in #1490. Please update to v3.0.5

**Comment by rschristian** [comment]
Closing as solution has been pointed out.
