### ISSUE TITLE
async! prefix in typescript not working

### ISSUE THREAD

**Issue by cspeter** [preactjs/preact-cli#560]
async! code splitting works just fine when the source is in js.
But if i switch to typescript the code is not splitted.
All works fine except async! prefix.
I already tried with "removeComments": false in tsconfig, and also tried to keep app.js in js.
But no luck.

**Comment by developit** [comment]
I think this might be an issue with `awesome-typescript-loader`, which is what `preact-cli-plugin-typescript` uses:
https://github.com/wub/preact-cli-plugin-typescript/blob/master/src/index.js#L17
/cc @wub

**Comment by mrnkr** [comment]
Just in case anyone is still struggling to find a solution to this problem I'll leave the one I just found (checked it with webpack bundle analyzer and chrome network monitor 🙃)

I used [preactjs-templates/typescript](https://github.com/preactjs-templates/typescript) and using bundle analyzer I saw I wasn't having my code split. After playing around with preact.config.js I found that the following configuration actually makes things work (thank God for webpack's docs which explained me how to run a loader after another):

```javascript
config.module.loaders.push({
    test: /\.tsx?$/,
    loader: 'async!ts-loader'
});
```

That, if I understood correctly (and it certainly looks like it) has preact-cli's async loader run after ts-loader, which makes code split as expected when bundling 😎.

Really hope this helps someone! I'll make a PR to that template in order to add this bit of code since it really feels like it should be there!

**Comment by douggr** [comment]
> Just in case anyone is still struggling to find a solution to this problem I'll leave the one I just found (checked it with webpack bundle analyzer and chrome network monitor upside_down_face)
> 
> I used [preactjs-templates/typescript](https://github.com/preactjs-templates/typescript) and using bundle analyzer I saw I wasn't having my code split. After playing around with preact.config.js I found that the following configuration actually makes things work (thank God for webpack's docs which explained me how to run a loader after another):
> 
> ```js
> config.module.loaders.push({
>     test: /\.tsx?$/,
>     loader: 'async!ts-loader'
> });
> ```
> 
> That, if I understood correctly (and it certainly looks like it) has preact-cli's async loader run after ts-loader, which makes code split as expected when bundling sunglasses.
> 
> Really hope this helps someone! I'll make a PR to that template in order to add this bit of code since it really feels like it should be there!

Thank you!

Playing with `preact-cli@next`, you need to upgrade `ts-loader` to latest (^5 atm).

**preact.conf.js**

```js
export default function(config, env, helpers) {
    config.module.rules.push({
        test: /\.tsx?$/,
        loader: 'async!ts-loader'
    });

    return config;
}

```

**Comment by mrnkr** [comment]
Since you've tried this I have to ask... Although my code did split and in my quick test it did work I found that the behavior I was getting was weird to say the least.

I mean: what happened is that my code did split but more than it should have. I can't remember what package it was but I know that it got split between two modules. When it was imported the first one would be loaded but the second module wouldn't and that lead to some exports being undefined, hence the entire app would crash because the module wasn't fully loaded.

I looked a bit at the async loader's code and thought it could be that it just didn't enforce any kind of logic as to how it splits, it just splits. I admit not having tried this with javascript so I wouldn't be able to rule out the possibility of me having made a mess of things myself.

The question is, of course, did you experience anything similar to this?

**Comment by douggr** [comment]
Hi @mrnkr!

In fact, I'm facing something like this. The code splits *randomly*, looks like it splits each component into a different chunk.

Breaking the app is also pretty random, when using `dev server`, everything goes just fine, but my app is now breaking with `Typings for CSS-Modules: option `modules` is not active - skipping extraction work...` and the **some** components do not compile. 

Unfortunately I don't have much time to dig further atm, going backing to JS version.

**Comment by mrnkr** [comment]
I did have the issue with `Typings for CSS-Modules` as well, removed that extension from preact.config and made that error go away but then all hell broke loose like I said...

At the moment I don't have much time to devote to this either but I guess it won't be long until I do. I like automatic code splitting too much to lose it and to me giving up typescript is a no-go!

Happy coding! I'll be back 😝

**Comment by ForsakenHarmony** [comment]
I think this is fixed by typescript support in core?

**Comment by SpaceHeroGuide** [comment]
This is still broken. 

1. Create a new empty project `preact create typescript async-test`
1. Change import in `src/components/app.tsx` to `import Profile from "async!../routes/profile";`

If you use `npm run start` code splitting will work. However if you run `npm run build` it will fail because of the async import (I had to delete the header.test.tsx file in test because of a typings error in react-router-spy). If you then upgrade ts-loader (`npm i ts-loader@5.0.0 --save`) and add @douggr code to preact.config.js, then both npm run commands will fail because of the import.

Any solutions for this? I though my project setup was causing problems but apparently it's not even working with the template projects.
